import type { Metadata } from "next";
import "./globals.css";

import { Navbar } from "@/components/Navbar";
import { MyProvider } from "../../redux/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative w-full h-full overflow-auto flex flex-col">
        <MyProvider>
          <Navbar />
          <main className="mx-auto w-full h-full p-4 text-black">
            {children}
          </main>
        </MyProvider>
      </body>
    </html>
  );
}
