import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='relative w-full h-full overflow-auto flex flex-col'>
        <Navbar />
        <main className="mx-auto w-full h-full p-4 text-black">
          {children}
        </main>
      </body>
    </html>
  )
}
